services:
  mysql:
    container_name: mysql_mvc
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mvc
      MYSQL_USER: andre
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
